### ISSUE TITLE
Visualizing the data fails

### ISSUE THREAD

**Issue by JHalili** [neheller/kits19#50]
The get_data() method in visualize.py fails with this Trace:
Traceback (most recent call last):
  File "/home/jp/kits19/starter_code/visualize.py", line 188, in <module>
    plane=args.plane
  File "/home/jp/kits19/starter_code/visualize.py", line 82, in visualize
    vol = vol.get_data()
  File "/usr/local/lib/python3.6/dist-packages/nibabel/deprecator.py", line 162, in deprecated_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nibabel/dataobj_images.py", line 208, in get_data
    data = np.asanyarray(self._dataobj)
  File "/home/bubu/.local/lib/python3.6/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/lib/python3.6/dist-packages/nibabel/arrayproxy.py", line 393, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/usr/local/lib/python3.6/dist-packages/nibabel/arrayproxy.py", line 360, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/usr/local/lib/python3.6/dist-packages/nibabel/arrayproxy.py", line 339, in _get_unscaled
    mmap=self._mmap)
  File "/usr/local/lib/python3.6/dist-packages/nibabel/volumeutils.py", line 523, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.6/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid code lengths set

**Comment by mjq93** [comment]
> The get_data() method in visualize.py fails with this Trace:
> Traceback (most recent call last):
> File "/home/jp/kits19/starter_code/visualize.py", line 188, in
> plane=args.plane
> File "/home/jp/kits19/starter_code/visualize.py", line 82, in visualize
> vol = vol.get_data()
> File "/usr/local/lib/python3.6/dist-packages/nibabel/deprecator.py", line 162, in deprecated_func
> return func(*args, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/nibabel/dataobj_images.py", line 208, in get_data
> data = np.asanyarray(self._dataobj)
> File "/home/bubu/.local/lib/python3.6/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
> return array(a, dtype, copy=False, order=order, subok=True)
> File "/usr/local/lib/python3.6/dist-packages/nibabel/arrayproxy.py", line 393, in **array**
> arr = self._get_scaled(dtype=dtype, slicer=())
> File "/usr/local/lib/python3.6/dist-packages/nibabel/arrayproxy.py", line 360, in _get_scaled
> scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
> File "/usr/local/lib/python3.6/dist-packages/nibabel/arrayproxy.py", line 339, in _get_unscaled
> mmap=self._mmap)
> File "/usr/local/lib/python3.6/dist-packages/nibabel/volumeutils.py", line 523, in array_from_file
> n_read = infile.readinto(data_bytes)
> File "/usr/lib/python3.6/gzip.py", line 276, in read
> return self._buffer.read(size)
> File "/usr/lib/python3.6/_compression.py", line 68, in readinto
> data = self.read(len(byte_view))
> File "/usr/lib/python3.6/gzip.py", line 471, in read
> uncompress = self._decompressor.decompress(buf, size)
> zlib.error: Error -3 while decompressing data: invalid code lengths set

I met the same error, do you have any solution?
